---
name: Test

on:
  push:
    branches:
      - test

env:
  NODE_VERSION: 18

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker Image
        working-directory: src
        run: |
          cp ../scripts/build_docker_image.sh .
          chmod +x build_docker_image.sh
          ./build_docker_image.sh
