---
name: Test

on:
  push:
    branches:
      - test

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: List files
        run: |
          ls -la
