---
name: Test

on:
  push:
    branches:
      - test

env:
  NODE_VERSION: 18

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker Image
        working-directory: src
        run: |
          docker build -t apix-nginx:v1.0.0 .
